"""final victory

Revision ID: 90fb478456aa
Revises: 
Create Date: 2025-11-30 16:36:47.759663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fb478456aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('pair_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starting_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('squat', sa.Float(), nullable=True),
    sa.Column('bench', sa.Float(), nullable=True),
    sa.Column('press', sa.Float(), nullable=True),
    sa.Column('deadlift', sa.Float(), nullable=True),
    sa.Column('powerclean', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workout_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(length=1), nullable=False),
    sa.Column('is_rest_day', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lift_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=50), nullable=False),
    sa.Column('working_weight', sa.Float(), nullable=False),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('warmup_data', sa.JSON(), nullable=True),
    sa.Column('work_sets_completed', sa.Integer(), nullable=True),
    sa.Column('work_sets_required', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lift_entry')
    op.drop_table('workout_log')
    op.drop_table('starting_weights')
    op.drop_table('plate')
    op.drop_table('user')
    # ### end Alembic commands ###
